name: country_list
description: Flutter package for receiving list of countries with codes and phone codes
version: 0.0.1
homepage: https://github.com/DevArtel/country_list

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0

dev_dependencies:
  flutter_lints: ^1.0.2

flutter:
  assets:
    - assets/i18n/
